.github/workflows/cicd.yml, src/main/java/com/javajober/core/util/HealthCheckController.java
=> GitHub Actions 활용한 CI / CD 프로세스 구축 완료

src/main/java/com/javajober/entity/MemberGroup.java
=> MemberGroup 엔티티 수정 완료

src/main/java/com/javajober/entity/TemplateAuth.java, src/main/resources/db/temporary.sql
=> TemplateAuth 엔티티 수정 완료

src/main/java/com/javajober/JavaJoberApplication.java, src/main/resources/application.yml
- #6
- @EnableJpaAuditing 어노테이션 추가
=> CI/CD 프로세스 구축 수정 완료

src/main/java/com/javajober/controller/TemplateBlockController.java, src/main/java/com/javajober/dto/MemberAuthResponse.java, src/main/java/com/javajober/entity/TemplateAuth.java, src/main/java/com/javajober/repository/AddSpaceRepository.java, src/main/java/com/javajober/repository/MemberGroupRepository.java, src/main/java/com/javajober/repository/TemplateAuthRepository.java, src/main/java/com/javajober/service/TemplateBlockService.java, src/main/resources/db/temporary.sql
- [#11]
이상하거나 고쳐야할게 있다면 알려주세요...🥲
=> 공유페이지 템플릿 권한 설정 API 구현

src/main/java/com/javajober/template/controller/TemplateBlockController.java, src/main/java/com/javajober/template/dto/MemberAuthResponse.java, src/main/java/com/javajober/template/repository/AddSpaceRepository.java, src/main/java/com/javajober/template/repository/MemberGroupRepository.java, src/main/java/com/javajober/template/repository/TemplateAuthRepository.java, src/main/java/com/javajober/template/service/TemplateBlockService.java
=> 템플릿 권한 설정 패키지 구조 수정 완료

src/main/java/com/javajober/entity/Template.java, src/main/java/com/javajober/template/controller/TemplateBlockController.java, src/main/java/com/javajober/template/dto/TemplateResponse.java, src/main/java/com/javajober/template/repository/SpaceWallCategoryRepository.java, src/main/java/com/javajober/template/repository/TemplateRepository.java, src/main/java/com/javajober/template/service/TemplateBlockService.java, src/main/resources/db/temporary.sql
- [#19 ]
오류, 오타 등 수정사항이 있다면 알려주세요~~ 🥰
=> 공유페이지 작성 추천 템플릿 API 구현

src/main/java/com/javajober/template/controller/TemplateBlockController.java, src/main/java/com/javajober/template/repository/TemplateRepository.java, src/main/java/com/javajober/template/service/TemplateBlockService.java
=> 공유페이지 작성 템플릿 검색 API 구현

.gitignore, build.gradle, src/main/java/com/javajober/core/fcm/FcmInitializer.java, src/main/resources/application.yml
=> Firebase 연동 및 FCM 초기화 환경 설정 완료

src/main/java/com/javajober/core/fcm/FcmInitializer.java, src/main/java/com/javajober/core/message/ErrorMessage.java
=> FCM 에러메시지 코드 수정 및 오류 메시지 추가 완료

src/main/java/com/javajober/core/message/SuccessMessage.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallContoller.java, src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/resources/db/temporary.sql
=> 공유페이지 임시 저장 내역 확인 API 수정완료

src/main/java/com/javajober/fcm/domain/MemberFcmToken.java, src/main/java/com/javajober/fcm/repository/MemberFcmTokenRepository.java, src/main/java/com/javajober/fcm/service/MemberFcmTokenService.java
=> FCM 토큰 저장 로직 추가 및 개선 완료

src/main/java/com/javajober/fcm/controller/MemberFcmTokenController.java, src/main/java/com/javajober/fcm/controller/SubscriptionController.java, src/main/java/com/javajober/fcm/domain/Subscription.java, src/main/java/com/javajober/fcm/dto/SubscriptionRequest.java, src/main/java/com/javajober/fcm/repository/SubscriptionRepository.java, src/main/java/com/javajober/fcm/service/SubscriptionService.java
=> 구독 버튼 기능 구현 완료

src/main/java/com/javajober/fcm/controller/SubscriptionController.java, src/main/java/com/javajober/fcm/repository/SubscriptionRepository.java, src/main/java/com/javajober/fcm/service/SubscriptionService.java
=> 구독 취소 기능 구현 완료

src/main/java/com/javajober/freeBlock/controller/FreeBlockController.java, src/main/java/com/javajober/freeBlock/domain/FreeBlock.java, src/main/java/com/javajober/freeBlock/dto/request/FreeBlockSaveRequest.java, src/main/java/com/javajober/freeBlock/dto/request/FreeBlockSaveRequests.java, src/main/java/com/javajober/freeBlock/dto/request/FreeBlockUpdateRequest.java, src/main/java/com/javajober/freeBlock/dto/request/FreeBlockUpdateRequests.java, src/main/java/com/javajober/freeBlock/dto/response/FreeBlockResponse.java, src/main/java/com/javajober/freeBlock/dto/response/FreeBlockResponses.java, src/main/java/com/javajober/freeBlock/repository/FreeBlockRepository.java, src/main/java/com/javajober/freeBlock/service/FreeBlockService.java
=> freeBlock Creat, Read, Update 구현

src/main/java/com/javajober/entity/Notification.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
- #49
- 멤버와 스페이스월 아이디로 SpaceWall 가져오는 로직 추가
=> 구독 취소 오류 코드 수정 완료 

src/main/java/com/javajober/template/controller/TemplateBlockController.java, src/main/java/com/javajober/template/dto/TemplateBlockDeleteRequest.java, src/main/java/com/javajober/template/dto/TemplateBlockRequest.java, src/main/java/com/javajober/template/dto/TemplateBlockResponses.java, src/main/java/com/javajober/template/repository/TemplateAuthRepository.java, src/main/java/com/javajober/template/repository/TemplateBlockRepository.java, src/main/java/com/javajober/template/service/TemplateBlockService.java
=> TemplateBlock CRUD 수정

src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/domain/SpaceWall.java, src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/resources/db/temporary.sql
=> SpaceWall 엔티티에 memberId 컬럼 추가에 따른 수정 완료

src/main/java/com/javajober/template/controller/TemplateBlockController.java, src/main/java/com/javajober/template/domain/TemplateAuth.java, src/main/java/com/javajober/template/domain/TemplateBlock.java, src/main/java/com/javajober/template/dto/TemplateBlockUpdateRequest.java, src/main/java/com/javajober/template/service/TemplateBlockService.java
=> TemplateBlock update 기능 구현

src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/resources/db/temporary.sql
=> 공유페이지 TemplateBlock Mapping 기능 구현

src/main/java/com/javajober/setting/controller/BackgroundSettingController.java, src/main/java/com/javajober/setting/controller/BlockSettingController.java, src/main/java/com/javajober/setting/controller/StyleSettingController.java, src/main/java/com/javajober/setting/controller/ThemeSettingController.java, src/main/java/com/javajober/setting/domain/BackgroundSetting.java, src/main/java/com/javajober/setting/domain/BlockSetting.java, src/main/java/com/javajober/setting/domain/StyleSetting.java, src/main/java/com/javajober/setting/domain/ThemeSetting.java, src/main/java/com/javajober/setting/dto/BackgroundSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/BlockSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/StyleSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/ThemeSettingSaveRequest.java, src/main/java/com/javajober/setting/repository/BackgroundSettingRepository.java, src/main/java/com/javajober/setting/repository/BlockSettingRepository.java, src/main/java/com/javajober/setting/repository/StyleSettingRepository.java, src/main/java/com/javajober/setting/repository/ThemeSettingRepository.java, src/main/java/com/javajober/setting/service/BackgroundSettingService.java, src/main/java/com/javajober/setting/service/BlockSettingService.java, src/main/java/com/javajober/setting/service/StyleSettingService.java, src/main/java/com/javajober/setting/service/ThemeSettingService.java
- [#70]
- 패키지 구조 변경 및 setting create 기능 구현
=> Setting create 기능 구현

.github/workflows/cicd.yml, src/main/resources/application-prod.yml
- #6 
- 배포 이슈로 인한 CI/CD 닫았다가 다시 오픈합니다.
=> GitHub Actions 활용한 CI / CD 프로세스 재구축 완료 

.ebextensions/nginx.conf, src/main/java/com/javajober/core/message/ErrorMessage.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/wallInfoBlock/dto/request/WallInfoBlockRequest.java, src/test/java/com/javajober/JavaJoberApplicationTests.java
=> WallInfoBlock, Fileblock MultipartFile 저장 기능 구현 완

src/main/java/com/javajober/core/config/WebMvcConfig.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
=> mutipartFile 오류 수정, CORS 설정 추가 완료

.ebextensions/nginx.conf, src/main/java/com/javajober/fileBlock/domain/FileBlock.java, src/main/java/com/javajober/fileBlock/dto/request/FileBlockSaveRequest.java, src/main/java/com/javajober/fileBlock/dto/request/FileBlockSaveRequests.java, src/main/java/com/javajober/fileBlock/service/FileBlockService.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/wallInfoBlock/dto/request/WallInfoBlockRequest.java
=> multipartFile 코드 제거 완료

src/main/java/com/javajober/setting/controller/BackgroundSettingController.java, src/main/java/com/javajober/setting/controller/StyleSettingController.java, src/main/java/com/javajober/setting/dto/BackgroundSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/BlockSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/StyleSettingSaveRequest.java, src/main/java/com/javajober/setting/dto/ThemeSettingSaveRequest.java, src/main/java/com/javajober/setting/service/BackgroundSettingService.java, src/main/java/com/javajober/setting/service/BlockSettingService.java, src/main/java/com/javajober/setting/service/StyleSettingService.java, src/main/java/com/javajober/setting/service/ThemeSettingService.java, src/main/java/com/javajober/spaceWall/dto/request/DataRequest.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/resources/application-dev.yml
=> StyleSetting Create 수정 및 Mapping 구현

src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
=> SpaceWallService save메소드 switch case문에 break 누락 수정 완료

src/main/java/com/javajober/core/message/SuccessMessage.java, src/main/java/com/javajober/space/controller/SpaceController.java, src/main/java/com/javajober/space/dto/MemberGroupResponse.java, src/main/java/com/javajober/space/dto/SpaceResponse.java, src/main/java/com/javajober/space/repository/MemberGroupRepository.java, src/main/java/com/javajober/space/repository/SpaceWallRepository.java, src/main/java/com/javajober/space/service/SpaceService.java
=> 개인/단체 스페이스 조회 및 공유페이지 유무 확인 API

src/main/java/com/javajober/template/service/TemplateService.java, src/main/java/com/javajober/templateBlock/repository/TemplateRepository.java
=> Template 카테고리 추천 enum으로 변경

src/main/java/com/javajober/template/repository/TemplateRepository.java, src/main/java/com/javajober/template/service/TemplateService.java
=>  템플릿 카테고리 별 조회 수정 

src/main/java/com/javajober/backgroundSetting/dto/response/BackgroundSettingResponse.java, src/main/java/com/javajober/blockSetting/dto/response/BlockSettingResponse.java, src/main/java/com/javajober/core/message/ErrorMessage.java, src/main/java/com/javajober/core/message/SuccessMessage.java, src/main/java/com/javajober/core/util/CommonResponse.java, src/main/java/com/javajober/fileBlock/dto/response/FileBlockResponse.java, src/main/java/com/javajober/freeBlock/dto/response/FreeBlockResponse.java, src/main/java/com/javajober/listBlock/dto/response/ListBlockResponse.java, src/main/java/com/javajober/listBlock/repository/ListBlockRepository.java, src/main/java/com/javajober/snsBlock/dto/response/SNSBlockResponse.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/domain/BlockType.java, src/main/java/com/javajober/spaceWall/dto/response/BlockResponse.java, src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java, src/main/java/com/javajober/spaceWall/dto/response/SpaceWallTemporaryResponse.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/styleSetting/dto/response/StyleSettingResponse.java, src/main/java/com/javajober/styleSetting/repository/StyleSettingRepository.java, src/main/java/com/javajober/templateBlock/dto/response/TemplateBlockResponse.java, src/main/java/com/javajober/themeSetting/dto/response/ThemeSettingResponse.java, src/main/java/com/javajober/wallInfoBlock/dto/response/WallInfoBlockResponse.java, src/main/java/com/javajober/wallInfoBlock/repository/WallInfoBlockRepository.java
=> 공유페이지 완성 (조회) API 구현 완료

src/main/java/com/javajober/core/message/SuccessMessage.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/domain/SpaceWall.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
=> 공유페이지 임시 저장 삭제 기능 구현 완료

src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/dto/request/DeleteTemporaryRequest.java
=> 임시 저장 삭제 엔드포인트 요청 및 파라미터 개선 완료

src/main/java/com/javajober/fileBlock/dto/request/FileBlockUpdateRequest.java, src/main/java/com/javajober/fileBlock/service/FileBlockService.java, src/main/java/com/javajober/listBlock/domain/ListBlock.java, src/main/java/com/javajober/listBlock/dto/request/ListBlockUpdateRequest.java, src/main/java/com/javajober/listBlock/repository/ListBlockRepository.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/domain/SpaceWall.java, src/main/java/com/javajober/spaceWall/dto/request/DataUpdateRequest.java, src/main/java/com/javajober/spaceWall/dto/request/SpaceWallUpdateRequest.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/templateBlock/service/TemplateBlockService.java, src/main/java/com/javajober/wallInfoBlock/domain/WallInfoBlock.java, src/main/java/com/javajober/wallInfoBlock/dto/request/WallInfoBlockUpdateRequest.java, src/main/java/com/javajober/wallInfoBlock/repository/WallInfoBlockRepository.java
=> 공유페이지 update 기능 구현

src/main/java/com/javajober/core/message/ErrorMessage.java, src/main/java/com/javajober/core/message/SuccessMessage.java, src/main/java/com/javajober/fileBlock/dto/request/FileBlockUpdateRequest.java, src/main/java/com/javajober/fileBlock/repository/FileBlockRepository.java, src/main/java/com/javajober/fileBlock/service/FileBlockService.java, src/main/java/com/javajober/freeBlock/repository/FreeBlockRepository.java, src/main/java/com/javajober/freeBlock/service/FreeBlockService.java, src/main/java/com/javajober/listBlock/repository/ListBlockRepository.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/domain/SpaceWall.java, src/main/java/com/javajober/spaceWall/dto/response/BlockResponse.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/styleSetting/repository/StyleSettingRepository.java, src/main/java/com/javajober/template/service/TemplateService.java, src/main/java/com/javajober/templateBlock/repository/TemplateBlockRepository.java, src/main/java/com/javajober/templateBlock/service/TemplateBlockService.java, src/main/java/com/javajober/wallInfoBlock/dto/response/WallInfoBlockResponse.java, src/main/java/com/javajober/wallInfoBlock/repository/WallInfoBlockRepository.java
=> 공유페이지 임시 저장 불러오기 API 구현 완료 

src/main/java/com/javajober/core/message/ErrorMessage.java, src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java, src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
=> SpaceWallService 수정 완료

src/main/java/com/javajober/core/message/ErrorMessage.java, src/main/java/com/javajober/memberGroup/repository/MemberGroupRepository.java, src/main/java/com/javajober/space/controller/SpaceController.java, src/main/java/com/javajober/space/dto/response/DataResponse.java, src/main/java/com/javajober/space/service/SpaceService.java
=> fix:스페이스 API 리스트 응답 에러 수정 #39

src/main/java/com/javajober/space/service/SpaceService.java, src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
=> 배포 후 오류로 인한 SpaceWall 조회 로직 수정 완료

src/main/java/com/javajober/space/controller/SpaceController.java
=> style:스페이스 컨트롤러 오타 수정 #39

src/main/java/com/javajober/fileBlock/domain/FileBlock.java, src/main/java/com/javajober/fileBlock/service/FileBlockService.java, src/main/java/com/javajober/spaceWall/service/FileUploadService.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
=> file추가로 인한 FileBlock 수정

src/main/java/com/javajober/space/service/SpaceService.java
=> fix:member_hashtag 기준으로 리스트 정렬 기능 추가 #39

src/main/java/com/javajober/spaceWall/service/FileUploadService.java, src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
=> WallInfoBlock update 순서 변경

src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java, src/main/java/com/javajober/styleSetting/dto/response/StyleSettingResponse.java
=> StyleSettingBlockId 추가 완료

src/main/java/com/javajober/spaceWall/domain/SpaceWall.java, src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
=> 임시 저장 공간 완전 삭제 로직으로 변경 완료

src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java, src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
=> 공유페이지 임시 저장 유무 확인 로직 수정 완료
